apiVersion: v1
kind: Service

metadata:
  name: kubernetes-demo-api-service     # Service name
  labels:
    app: kubernetes-demo-api            # Label for identification

spec:
  selector:
    app: kubernetes-demo-api            # Must match pod labels

  ports:
    - protocol: TCP
      port: 3000                        # Service port (cluster-facing)
      targetPort: 3000                  # Container port

  type: NodePort                        # Use LoadBalancer in cloud
